backend:
  name: git-gateway
  branch: master
publish_mode: "editorial_workflow"
media_folder: "assets/images/uploads"
logo_url: "logo.png"
site_url: https://92crew.com
display_url: https://92crew.com
collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Intro", name: "intro", widget: "string"}
      - {label: "Feature Image (1000 x 1000)", name: "feature-image", widget: "image" }
      - {label: "Hero Image (1920 x 624)", name: "hero-image", widget: "image" }
      - {label: "Date", name: "date", widget: "datetime" }
      - {label: "Featured", name: "featured", widget: "boolean" }
      - {label: "Body", name: "body", widget: "markdown"}
